FROM node:16 as builder

WORKDIR /app/server

COPY package*.json .
COPY yarn.lock .

# Install dependencies
RUN npm install

COPY . .

# Final Image
FROM node:16

WORKDIR /app/server


COPY --from=builder /app/server .

# Environment variables
ARG MONGO_URI
ARG PORT
ARG NODE_ENV
ENV MONGO_URI=${MONGO_URI}
ENV PORT=${PORT}
ENV NODE_ENV=${NODE_ENV}

EXPOSE 4000

CMD ["node", "src/server.js"]