version: "3.8"

services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client.staging
    image: localhost:5000/client:staging # Use fully qualified image names
    ports:
      - "8080:8080"
    stdin_open: true

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server.staging
    image: localhost:5000/server:staging # Use fully qualified image names
    environment:
      - MONGO_URI=mongodb://db:27017/db # Correct MongoDB connection string
      - PORT=4000
      - NODE_ENV=production
    command: node src/server.js

  db:
    image: localhost:5000/mongo:staging # Use a tagged version for consistency
    environment:
      - MONGO_INITDB_ROOT_USERNAME=abdelaali # Use variable interpolation
      - MONGO_INITDB_ROOT_PASSWORD=Abdellaali2550
    volumes:
      - db_staging:/data/db

volumes:
  db_staging:
