FROM jenkins/jenkins:lts-slim

USER root

# Install Docker and Docker Compose
RUN apt update && apt install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg2 \
    software-properties-common && \
    curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" \
    -o /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && \
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian buster stable" > /etc/apt/sources.list.d/docker.list && \
    apt update && apt install -y \
        docker-ce=5:20.10.25~3-0~debian \
        docker-ce-cli=5:20.10.25~3-0~debian \
        containerd.io=1.6.21-1 && \
    sed -i 's/^docker.*$/docker:x:998:jenkins/' /etc/group && \
    usermod -a -G docker jenkins && \
    rm -rf /var/lib/apt/lists/*

ENV JAVA_ARGS="-Djava.net.preferIPv4Stack=true"
